development:
  adapter: postgresql
  database: treehugger_dev
  encoding: unicode
  host: localhost
  pool: 25

test:
  adapter: postgresql
  database: treehugger_test

production:
  adapter: postgresql
  database: treehugger_prod
	username: <%= ENV["PG_USERNAME"] %>
	password: <%= ENV["PG_PASSWORD"] %>