development:
  adapter: postgresql
  encoding: utf8
  database: treehugger_dev 
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: treehugger_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: treehugger_prod
  pool: 5
  username: 
  password: